### ISSUE TITLE
feature implement: tags

### ISSUE THREAD

**Issue by the-arcade-01** [the-arcade-01/Sociot#5]
- [x] tags container on home page
- [x] fetch and populate tags using backend api
- [x] tags input box in create post modal
- [x] changes in create post modal req body

**Comment by the-arcade-01** [comment]
@Aravind-27 you can work on this issue

**Comment by Aravind-27** [comment]
Ok

**Comment by Aravind-27** [comment]
Please Review https://github.com/the-arcade-01/sociot/pull/7

**Comment by the-arcade-01** [comment]
have been completed in 837c1715bc5ec3d4263f105de97db3bb85795a7c and 11e42d3e064d20e9a82925608ce2bad47638c9bf
